//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> IDdate { get; set; }
        public Nullable<int> Total { get; set; }
        public string PatientID { get; set; }
        public string AccountID { get; set; }
        public string ExamID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ExaminationForm ExaminationForm { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
