//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDetail
    {
        public string ExamID { get; set; }
        public string MedicineID { get; set; }
        public string UsageID { get; set; }
        public int Quantity { get; set; }
    
        public virtual ExaminationForm ExaminationForm { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual MedicineUsage MedicineUsage { get; set; }
    }
}
